paths:
  /store/addReview:
    post:
      tags:
        - store
      summary: 리뷰등록
      parameters:
      - name: addReview
        in: body
        required: true
        schema:
          properties:
            user_id:
              type: string
              description: 유저 아이디
              example: swagger123
            store_id:
              type: string
              description: 가게 아이디
              example: store123
            review_id:
              type: string
              description: 리뷰 아이디
              example: review123
            title:
              type: string
              description: 타이틀
              example: 이집잘하네
            body:
              type: string
              description: 내용
              example: 아주 맛도리에요. 하핳. 잘 먹고갑니다.
            score:
              type: integer
              description: 평점
              example: 3
      responses:
        '200':
          description: 리뷰 등록 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: {
                  "user_id": "swagger123",
                  "store_id": "store123",
                  "review_id": "review123"
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  /store/addMission:
    post:
      tags:
        - store
      summary: 미션등록
      parameters:
      - name: addMission
        in: body
        required: true
        schema:
          properties:
            user_id:
              type: string
              description: 미션 아이디
              example: swagger123
            store_id:
              type: string
              description: 가게 아이디
              example: store123
            title:
              type: string
              description: 타이틀
              example: 대표메뉴 먹기(마르게리따)
            body:
              type: string
              description: 내용
              example: 본 지점에 방문해서 가게 대표메뉴 시켜서 먹어보기
            score:
              type: integer
              description: 보상
              example: 3
      responses:
        '200':
          description: 미션 등록 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: {
                  "mission_id": "mission123",
                  "store_id": "store123"
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  /{storeId}/reviews:
    get:
      tags:
        - Store
      summary: 가게 별 리뷰 조회 로직
      parameters:
        - name: storeId
          in: path
          schema:
            type: integer
          required: true
        - name: reviewId
          in: query
          required: false
          schema:
            properties:
              reviewId:
                type: integer
        - name: paging
          in: query
          required: true
          schema:
            properties:
              size:
                type: integer
      responses:
        '200':
          description: 리뷰 조회 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: array
                example: {
                  "reviewData": [
                    {
                      "user_name": "SwaggerTest1",
                      "rate": 5,
                      "review_body": "리뷰1",
                      "create_date": "2000.01.01"
                    },
                    {
                      "user_name": "SwaggerTest2",
                      "rate": 4.5,
                      "review_body": "리뷰2",
                      "create_date": "2000.02.02"
                    }
                  ],
                  "cursorId": 1
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  /{storeId}/missions:
    get:
      tags:
        - Store
      summary: 가게 별 미션 조회 로직
      parameters:
        - name: storeId
          in: path
          schema:
            type: integer
          required: true
        - name: missionId
          in: query
          required: false
          schema:
            properties:
              reviewId:
                type: integer
        - name: paging
          in: query
          required: true
          schema:
            properties:
              size:
                type: integer
      responses:
        '200':
          description: 리뷰 조회 성공
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: array
                example: {
                  "reviewData": [
                    {
                      "store_name": "Swagger",
                      "mission_id": "SwaggerTest1",
                      "mission_title": "mission_title",
                      "mission_reward": 5,
                      "mission_body": "대방어 먹고싶다",
                      "create_date": "2000.01.01"
                    },
                    {
                      "store_name": "Swagger1",
                      "mission_id": "SwaggerTest2",
                      "mission_title": "mission_title",
                      "mission_reward": 5,
                      "mission_body": "소주랑 먹고싶다",
                      "create_date": "2000.01.01"
                    }
                  ],
                  "cursorId": 1
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.