paths:
  /store/addReview:
    post:
      tags:
        - store
      summary: 리뷰등록
      parameters:
      - name: addReview
        in: body
        required: true
        schema:
          properties:
            user_id:
              type: string
              description: 유저 아이디
              example: swagger123
            store_id:
              type: string
              description: 가게 아이디
              example: store123
            review_id:
              type: string
              description: 리뷰 아이디
              example: review123
            title:
              type: string
              description: 타이틀
              example: 이집잘하네
            body:
              type: string
              description: 내용
              example: 아주 맛도리에요. 하핳. 잘 먹고갑니다.
            score:
              type: integer
              description: 평점
              example: 3
      responses:
        '200':
          description: 리뷰 등록 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: {
                  "user_id": "swagger123",
                  "store_id": "store123",
                  "review_id": "review123"
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.